package in.careerscale.training.hibernate.model;

// Generated 17 Feb, 2014 8:09:00 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Designation generated by hbm2java
 */
@Entity
@Table(name = "designation", catalog = "office", uniqueConstraints = @UniqueConstraint(columnNames = "title"))
public class Designation implements java.io.Serializable {

	private Integer id;
	private String title;
	private Set<Employee> employees = new HashSet<Employee>(0);

	public Designation() {
	}

	public Designation(String title, Set<Employee> employees) {
		this.title = title;
		this.employees = employees;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "title", unique = true, length = 45)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "designation")
	public Set<Employee> getEmployees() {
		return this.employees;
	}

	public void setEmployees(Set<Employee> employees) {
		this.employees = employees;
	}

}
